### ISSUE TITLE
[BUG] Rollup job throws exception.

### ISSUE THREAD

**Issue by neographikal** [opendistro-for-elasticsearch/index-management#364]
**Describe the bug**
New rollup job throws error in GUI and log, Source data is mqtt data ingested with telegraf from mqtt.

**Other plugins installed**
Box standard odfe-elasticsearch docker container 1.12.0

**To Reproduce**
![1](https://user-images.githubusercontent.com/2643715/103170515-07754000-4845-11eb-8b11-ba5f57e266c9.png)
![2](https://user-images.githubusercontent.com/2643715/103170517-09d79a00-4845-11eb-832c-b8a4cb1e213d.png)
![3](https://user-images.githubusercontent.com/2643715/103170518-0c39f400-4845-11eb-8539-9a5e23f60d6b.png)

Result GUI:
![result](https://user-images.githubusercontent.com/2643715/103170527-1d830080-4845-11eb-9e07-2c59874e655c.png)

Logfile:

[log.txt](https://github.com/opendistro-for-elasticsearch/index-management/files/5744528/log.txt)

**Expected behavior**
Roll up index and not throw an error

**Screenshots**

**Desktop (please complete the following information):**
Opendistro 1.12.0

**Additional context**

**Comment by WassimDhib** [comment]
Hi

I have the same issue with rollup job on odfe-1.12.0 in docker :   `java.lang.IllegalArgumentException: can not write type [class java.time.Instant]`

This is my configuration :

![image](https://user-images.githubusercontent.com/30473593/103341964-8e662a80-4a88-11eb-8d70-729af6dd9594.png)





This is the full stacktrace :


```
[2020-12-30T08:59:23,900][INFO ][c.a.o.j.s.JobScheduler   ] [node2] Scheduling job id heartbeat-rollup for index .opendistro-ism-config .
[2020-12-30T08:59:24,496][WARN ][o.e.t.OutboundHandler    ] [node2] send message failed [channel: Netty4TcpChannel{localAddress=/10.0.1.198:57856, remoteAddress=10.0.1.196/10.0.1.196:9300}]
java.lang.IllegalArgumentException: can not write type [class java.time.Instant]
        at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:848) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.index.query.RangeQueryBuilder.doWriteTo(RangeQueryBuilder.java:116) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.index.query.AbstractQueryBuilder.writeTo(AbstractQueryBuilder.java:79) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:1115) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalNamedWriteable(StreamOutput.java:1126) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.search.builder.SearchSourceBuilder.writeTo(SearchSourceBuilder.java:301) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalWriteable(StreamOutput.java:976) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.search.internal.ShardSearchRequest.innerWriteTo(ShardSearchRequest.java:266) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.search.internal.ShardSearchRequest.writeTo(ShardSearchRequest.java:255) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.transport.OutboundMessage.writeMessage(OutboundMessage.java:87) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.transport.OutboundMessage.serialize(OutboundMessage.java:64) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.transport.OutboundHandler$MessageSerializer.get(OutboundHandler.java:163) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.transport.OutboundHandler$MessageSerializer.get(OutboundHandler.java:149) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.transport.OutboundHandler$SendContext.get(OutboundHandler.java:196) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.transport.OutboundHandler.internalSend(OutboundHandler.java:130) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.transport.OutboundHandler.sendMessage(OutboundHandler.java:125) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.transport.OutboundHandler.sendRequest(OutboundHandler.java:89) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.transport.TcpTransport$NodeChannels.sendRequest(TcpTransport.java:270) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:747) [elasticsearch-7.10.0.jar:7.10.0]
        at com.amazon.opendistroforelasticsearch.security.transport.OpenDistroSecurityInterceptor.sendRequestDecorate(OpenDistroSecurityInterceptor.java:188) [opendistro_security-1.12.0.0.jar:1.12.0.0]
        at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin$7$2.sendRequest(OpenDistroSecurityPlugin.java:661) [opendistro_security-1.12.0.0.jar:1.12.0.0]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:661) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:712) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.SearchTransportService.sendCanMatch(SearchTransportService.java:116) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.CanMatchPreFilterSearchPhase.executePhaseOnShard(CanMatchPreFilterSearchPhase.java:88) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.lambda$performPhaseOnShard$3(AbstractSearchAsyncAction.java:244) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.performPhaseOnShard(AbstractSearchAsyncAction.java:279) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.run(AbstractSearchAsyncAction.java:215) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:365) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.start(AbstractSearchAsyncAction.java:182) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:685) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.TransportSearchAction.executeLocalSearch(TransportSearchAction.java:511) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.TransportSearchAction.lambda$executeRequest$3(TransportSearchAction.java:303) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:114) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:87) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:346) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:229) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:105) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:179) [elasticsearch-7.10.0.jar:7.10.0]
        at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.actionfilter.FieldCapsFilter.apply(FieldCapsFilter.kt:95) [opendistro_index_management-1.12.0.1.jar:1.12.0.1]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:177) [elasticsearch-7.10.0.jar:7.10.0]
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply0(OpenDistroSecurityFilter.java:263) [opendistro_security-1.12.0.0.jar:1.12.0.0]
        at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply(OpenDistroSecurityFilter.java:151) [opendistro_security-1.12.0.0.jar:1.12.0.0]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:177) [elasticsearch-7.10.0.jar:7.10.0]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:72) [opendistro_performance_analyzer-1.12.0.0.jar:1.12.0.0]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:177) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:155) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:83) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:86) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:75) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:412) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:545) [elasticsearch-7.10.0.jar:7.10.0]
        at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.RollupSearchService$executeCompositeSearch$2$1.invoke(RollupSearchService.kt:113) [opendistro_index_management-1.12.0.1.jar:1.12.0.1]
        at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.RollupSearchService$executeCompositeSearch$2$1.invoke(RollupSearchService.kt:45) [opendistro_index_management-1.12.0.1.jar:1.12.0.1]
        at com.amazon.opendistroforelasticsearch.indexmanagement.elasticapi.ElasticExtensionsKt.suspendUntil(ElasticExtensions.kt:127) [opendistro_index_management-1.12.0.1.jar:1.12.0.1]
        at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.RollupSearchService$executeCompositeSearch$2.invokeSuspend(RollupSearchService.kt:109) [opendistro_index_management-1.12.0.1.jar:1.12.0.1]
        at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.RollupSearchService$executeCompositeSearch$2.invoke(RollupSearchService.kt) [opendistro_index_management-1.12.0.1.jar:1.12.0.1]
        at com.amazon.opendistroforelasticsearch.indexmanagement.elasticapi.ElasticExtensionsKt.retry(ElasticExtensions.kt:94) [opendistro_index_management-1.12.0.1.jar:1.12.0.1]
        at com.amazon.opendistroforelasticsearch.indexmanagement.elasticapi.ElasticExtensionsKt.retry$default(ElasticExtensions.kt:87) [opendistro_index_management-1.12.0.1.jar:1.12.0.1]
        at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.RollupSearchService.executeCompositeSearch(RollupSearchService.kt:107) [opendistro_index_management-1.12.0.1.jar:1.12.0.1]
        at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.RollupRunner.runRollupJob(RollupRunner.kt:280) [opendistro_index_management-1.12.0.1.jar:1.12.0.1]
        at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.RollupRunner$runRollupJob$1.invokeSuspend(RollupRunner.kt) [opendistro_index_management-1.12.0.1.jar:1.12.0.1]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) [kotlinx-coroutines-core-1.3.7.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-1.3.7.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) [kotlinx-coroutines-core-1.3.7.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-1.3.7.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-1.3.7.jar:?]
[2020-12-30T08:59:24,531][WARN ][o.e.t.OutboundHandler    ] [node2] send message failed [channel: Netty4TcpChannel{localAddress=/10.0.1.198:52560, remoteAddress=10.0.1.197/10.0.1.197:9300}]
java.lang.IllegalArgumentException: can not write type [class java.time.Instant]

```

**Comment by dbbaughe** [comment]
Seems like it might be an issue with the continuous rollup job type, taking a look.

**Comment by dbbaughe** [comment]
@qreshi was able to find the issue and pushed out a fix, it'll be fixed in the next release.

**Comment by dbbaughe** [comment]
For anyone need fixed artifact now it's available from workflow:
https://github.com/opendistro-for-elasticsearch/index-management/actions/runs/467574583

Otherwise will be in the next ODFE release, thanks!

**Comment by neographikal** [comment]
Thanks!
