### ISSUE TITLE
[BUG] Metadata fails to initialize from certain date formats for continuous rollups

### ISSUE THREAD

**Issue by qreshi** [opendistro-for-elasticsearch/index-management#374]
This was a bug discovered when attempting to rollup on a time field that does not conform to `ISO_ZONED_DATE_TIME`.

The timestamp is parsed into a `ZonedDateTime` object as part of calculating the start and end time of a continuous rollup:
https://github.com/opendistro-for-elasticsearch/index-management/blob/c1e0f1f0a7878d40f8e5764e61b582358e13ca9b/src/main/kotlin/com/amazon/opendistroforelasticsearch/indexmanagement/rollup/RollupMetadataService.kt#L209-L221

-----

When the parsing fails, the metadata fails to initialize. So far this was only encountered with a data format of `yyyy-MM-dd HH:mm:ss` leading to an exception like the following being logged out:
```
[2021-01-06T13:54:45,877][ERROR][c.a.o.i.r.RollupRunner   ] [integTest-0] Failed to initialize rollup metadata
java.time.format.DateTimeParseException: Text '2018-11-28 15:52:25' could not be parsed at index 10
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2050) ~[?:?]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1952) ~[?:?]
	at java.time.ZonedDateTime.parse(ZonedDateTime.java:599) ~[?:?]
	at java.time.ZonedDateTime.parse(ZonedDateTime.java:584) ~[?:?]
	at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.RollupMetadataService.getRoundedTime(RollupMetadataService.kt:215) ~[opendistro_index_management-1.12.0.1-SNAPSHOT.jar:1.12.0.1-SNAPSHOT]
	at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.RollupMetadataService.getInitialStartTime(RollupMetadataService.kt:197) ~[opendistro_index_management-1.12.0.1-SNAPSHOT.jar:1.12.0.1-SNAPSHOT]
	at com.amazon.opendistroforelasticsearch.indexmanagement.rollup.RollupMetadataService$getInitialStartTime$1.invokeSuspend(RollupMetadataService.kt) ~[opendistro_index_management-1.12.0.1-SNAPSHOT.jar:1.12.0.1-SNAPSHOT]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) [kotlinx-coroutines-core-1.3.7.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-1.3.7.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) [kotlinx-coroutines-core-1.3.7.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-1.3.7.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-1.3.7.jar:?]
```

**Comment by pmarjou22** [comment]
Hello,
 Yes same behavior on epoch millis

[2021-01-13T20:49:59,643][ERROR][c.a.o.i.r.RollupRunner ] [ES_DATA_0] Failed to initialize rollup metadata 
java.time.format.DateTimeParseException: Text '1610221489205' could not be parsed at index 0 
 at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046) ~[?:?]

**Comment by qreshi** [comment]
Hi @pmarjou22,

A fix for this bug has been merged into the `master` and `opendistro-1.12` branches. If you would like to start using it right away you can download the artifact from [one of the recent automated workflow runs](https://github.com/opendistro-for-elasticsearch/index-management/actions/runs/484551391#artifacts).

**Comment by misterbayne** [comment]
I am trying the fix for this issue and I do not see the job running on the specified schedule. I have tried a fixed interval and cron expression but they both behave the same way. In my testing, I am aggregating the timestamp every hour. It seems that the job is running on that schedule because the rollup index only updates at the top of every hour.

**Comment by dbbaughe** [comment]
Hey @misterbayne,

Could you explain a bit more?

For clarification when you use a continuous job you have two different kinds of intervals. The date histogram interval that you are rolling up, i.e. the timestamp you are aggregating every hour. And the continuous rollup schedule interval. If you have the rollup schedule interval set to something much quicker, say 5 minutes, what that means is the job should try to run every 5 minutes and check if there is new data to rollup. But, because it does not do incremental rollups it needs to also wait for a full 1 hours worth of data according to the aggregation interval you specified, i.e. an hour. So it might be executing the job every 5 minutes, but that's just constantly checking if there's a new 1 hours worth of data.

**Comment by misterbayne** [comment]
Thank you for clearing that up. I was under the impression that I would see the job running every 5 minutes in the logs. My testing had the date histogram interval set to 1 hour and the rollup schedule interval set to 5 minutes. Your explanation makes complete sense as to why I would only see the data getting rolled up around the top of the hour.
Is there a best practices method you would recommend for configuring a rollup job for metrics by the day on an index that does a daily rollover?
Is there a way to use the API to load a rollup job (like there is for an index policy)?

**Comment by pmarjou22** [comment]
thanks @qreshi the fix you provided unlocked the situation, we now can start using rollup feature on our side
