### ISSUE TITLE
[BUG] ElasticSearch ISM plugin V 1.12.0.1 stand alone Installation Error 

### ISSUE THREAD

**Issue by susmitasain** [opendistro-for-elasticsearch/index-management#454]
**Describe the bug**
On Elastic Search Version 7.10.0 I was trying to  stand alone install opendistro ISM plugin - opendistro_index_management - 1.12.0.1  as per compatibility charts - [https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#plugin-compatibility].

Trying to download using [sudo bin/elasticsearch-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro-index-management-1.12.0.1.zip]  but the following URL is forbidden.

**Other plugins installed**
opendistro-job-scheduler-1.12.0.0
 
**To Reproduce**
1. Navigate to the Elasticsearch home directory for V 7.10.0

2. Run sudo bin/elasticsearch-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-job-scheduler/opendistro-job-scheduler-1.12.0.0.zip

3. Run sudo bin/elasticsearch-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro-index-management-1.12.0.1.zip

4. See below error  - 
`-> Installing https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro-index-management-1.12.0.1.zip
-> Downloading https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro-index-management-1.12.0.1.zip
-> Failed installing https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro-index-management-1.12.0.1.zip
-> Rolling back https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro-index-management-1.12.0.1.zip
-> Rolled back https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro-index-management-1.12.0.1.zip
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro-index-management-1.12.0.1.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1932)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:448)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:329)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:251)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)`

**Expected behavior**
The ISM plugin should have installed .

**Comment by guimarca** [comment]
It happened me today. It turns out that version of the plugin was named using underscores instead of dashes. This works:

`/usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro_index_management-1.12.0.1.zip`
