### ISSUE TITLE
Elastic don't start after install ISM

### ISSUE THREAD

**Issue by r00t9** [opendistro-for-elasticsearch/index-management#54]
I install ISM, everything it was ok i tried to upgrade the elastic version then i go back to 7.0.1 and i get this error from elastic 

> Exception in thread "main" ElasticsearchException[java.io.IOException: failed to read /var/lib/elasticsearch/nodes/0/indices/B20JPahlQ9y6vD3i2VCLGg/_state/state-13.st]; nested: IOException[failed to read /var/lib/elasticsearch/nodes/0/indices/B20JPahlQ9y6vD3i2VCLGg/_state/state-13.st]; nested: IllegalStateException[Can't get text on a VALUE_NULL at -1:7812];
	at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:165)
	at org.elasticsearch.gateway.MetaDataStateFormat.loadGeneration(MetaDataStateFormat.java:414)

**Comment by jinsoor-amzn** [comment]
Hi,

Can you please clarify on how you "upgrade the elastic version" and how you "then go back to 7.0.1"? If you can provide us with step by step to reproduce this issue, we will be able to help you with more detail.

**Comment by r00t9** [comment]
Hello i upgrade the latest version of opendistro, i tried to start the elastic but it was not start because of the opendistro index management plugin. I tried to downgrade also don't start. 

OS version: Ubuntu 18.04.2
I make all the steps here:  [opendistro-rolling-upgrade](https://opendistro.github.io/for-elasticsearch-docs/docs/upgrade/rolling/)

For downgrade just i run this:

`apt install  opendistroforelasticsearch=1.0.2-1 elasticsearch-oss=7.0.1  opendistro-job-scheduler=1.0.0.1-1 opendistro-performance-analyzer=1.0.0.0-1 opendistro-security=1.0.0.1-1 opendistro-sql=1.0.0.0-1 opendistro-alerting=1.0.0.0-1`
